[build]
builder = "nixpacks"

[deploy]
startCommand = "cd application && npm run builddb && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
